### ISSUE TITLE
Error when initializing RedisMemoryServer in global Jest setup

### ISSUE THREAD

**Issue by aleccool213** [mhassan1/redis-memory-server#5]
## Description

I prefer to use a Jest Global setup file when downloading binaries as opposed to letting it happen during the first occurrence in a test file. This makes it so I don't have to modify Jest timeouts to accommodate for the binary taking longer than the Jest default timeout to download and install, etc

When I try to do this with redis-memory-server, I get some errors. This may be due to the Jest global setup file being in native Node.js and having no TypeScript transformer and the library not being tested to work with native Node.js.

## Reproduction Steps

1. Git clone the reproduction repository at: 
2. `npm i`
3. Inspect the global setup file at `jest.global-setup.js`

```javascript
const RedisMemoryServer = require("redis-memory-server");

module.exports = async () => {
  const redis = await RedisMemoryServer();
  await redis.stop();
};
```

4. `npm t`
5. See failures in console

```
❯ npm t                                                                                                               15:59:39

> test-redis-memory-server@1.0.0 test /Users/[REDACTED]/Github/test-redis-memory-server
> jest

TypeError: Jest: Got error running globalSetup - /Users/[REDACTED]/Github/test-redis-memory-server/jest.global-setup.js, reason: RedisMemoryServer is not a function
    at module.exports (/Users/[REDACTED]/Github/test-redis-memory-server/jest.global-setup.js:4:23)
    at /Users/[REDACTED]/Github/test-redis-memory-server/node_modules/@jest/core/build/runGlobalHook.js:125:19
    at ScriptTransformer.requireAndTranspileModule (/Users/alecbrunelle/Github/test-redis-memory-server/node_modules/@jest/transform/build/ScriptTransformer.js:895:24)
    at async _default (/Users/[REDACTED]/Github/test-redis-memory-server/node_modules/@jest/core/build/runGlobalHook.js:116:9)
    at async runJest (/Users/[REDACTED]/Github/test-redis-memory-server/node_modules/@jest/core/build/runJest.js:352:5)
    at async _run10000 (/Users/[REDACTED]/Github/test-redis-memory-server/node_modules/@jest/core/build/cli/index.js:408:7)
    at async runCLI (/Users/[REDACTED]/Github/test-redis-memory-server/node_modules/@jest/core/build/cli/index.js:261:3)
    at async Object.run (/Users/[REDACTED]/Github/test-redis-memory-server/node_modules/jest/node_modules/jest-cli/build/cli/index.js:163:37)
npm ERR! Test failed.  See above for more details.
```

**Comment by mhassan1** [comment]
Please look more closely at the README. I don't think `await RedisMemoryServer()` is a valid way to use this library. This should work:
```js
const { RedisMemoryServer } = require('redis-memory-server')
module.exports = async () => {
  const redis = new RedisMemoryServer()
  const host = await redis.getHost()
  // ...
  await redis.stop()
}
```

**Comment by aleccool213** [comment]
Meant to use `new` 😵

Thanks
